name: Create new release

on:
  push:
    branches:
    - 'main'
    - 'beta'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v3
    - name: Use Node.js
      id: use-nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      id: install-dependencies
      run: yarn install --frozen-lockfile
    - name: Execute tests
      id: yarn-test
      run: yarn test
    - name: Prepare git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Create new version
      run: |
        yarn config set version-git-tag true
        yarn version --patch
    - name: Execute building
      id: yarn-build
      run: yarn build
    - name: Generate package
      id: yarn-pack
      run: yarn pack --filename bits-cr-middy-joi-validator.tgz
    - name: Upload package to artifacts
      id: upload-tgz-artifact
      uses: actions/upload-artifact@v3
      with:
        name: bits-cr-middy-joi-validator.tgz
        path: bits-cr-middy-joi-validator.tgz
    - name: Publish to npmjs.org
      id: publish-to-npm
      run: yarn publish bits-cr-middy-joi-validator.tgz
      env:
       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Setup github npm registry
      id: registry-npm-github
      uses: actions/setup-node@v3
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: Publish to npm.pkg.github.com
      id: publish-to-npm-github
      run: yarn publish bits-cr-middy-joi-validator.tgz
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push changes and release tag
      run: |
        git push origin
        git push origin --tags