name: Run tests

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
    - 'beta'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
        - '12'
        - '14'
        - '16'
      fail-fast: true
    
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node }}
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      id: install-dependencies
      run: yarn install --frozen-lockfile
    - name: Execute tests
      id: yarn-test
      run: yarn test